name: 叮咚买菜助手
addr: :9999 # web服务端口号 多开需修改为其他端口号
meituan:
  station:  # [美团买菜]站点ID 抓包 https://mall.meituan.com/api/c/poi/{station}/notice
  monitor_needed: false
  monitor_success_wait: 10
  notify_needed: true
dingdong:
  im_secret:  # 用户密钥
  base_concurrency: 1 # 除了提交订单的其他请求并发数, 默认为1
  submit_concurrency: 2 # 最后提交订单的并发数, 默认为2
  snap_up: 0 # 抢购, 0 关闭, 1 六点抢, 2 八点半抢, 3 六点和八点半都抢
  advance_time: 30 # 抢购提前进入准备时间, 单位:秒, 默认为30秒
  pick_up_needed: false # 闲时捡漏开关, false 关闭, true 打开, 在抢购高峰期之外的时间捡漏
  monitor_needed: true # 监听开关, 监听是否有可运力
  monitor_success_wait: 10 # 成功监听(发起捡漏或通知)之后的休息时间, 单位:分钟, 默认为10分钟
  notify_needed: true # 通知开关, 发现运力时或捡漏成功时的通知, 使用需同时打开监听或捡漏
  audio_needed: true # 播放音频开关, 在订单提交成功后播放音频
  pay_type: 4 # 支付方式 1现金 2支付宝 3微信公众号 4微信 5支付宝WAP 6微信小程序
bark: # Bark 用户组, 苹果使用 Bark 推送通知, 可以添加多个与你同属一个叮咚发货站点的用户
  - xxx # xxx 替换为你自己的 Bark token, 域名默认为"https://api.day.app/", 如果你的域名与默认不一致, 需要加上域名前缀
  - yyy # 其他的 token
push_plus: # PushPlus 用户组, 安卓和苹果都可使用 PushPlus 通过微信通知, 可以添加多个与你同属一个叮咚发货站点的用户
  - xxx # xxx 替换为你自己的 PushPlus token
  - yyy # 其他的 token
